services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpass
      - POSTGRES_DB=kram
      - PGPORT=5132
    restart: unless-stopped
    volumes:
      - ./db:/app/postgresql/data
  kram:
    depends_on:
      - postgres
    build: .
    restart: unless-stopped
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
